### ISSUE TITLE
FileNotFoundError: (Errno 21 No such file or directory: '/content/Wav2Lip/results/result voice.mp4'

### ISSUE THREAD

**Issue by techinAI** [Rudrabha/Wav2Lip#525]
<img width="1309" alt="Screenshot 2023-07-11 at 10 15 35 PM" src="https://github.com/Rudrabha/Wav2Lip/assets/8232719/4b2db346-2c76-4cf4-91e4-fe0a08d481fb">
It worked the first time. Then same issue occuring over and over again. Tried to look for it but cant find it.

**Comment by ramayanbindas** [comment]
I faced the same issue but can't figure what is missing

**Comment by osmania101** [comment]
same issue

**Comment by Akash-Jariwala** [comment]
_result_voice.mp4_ file is not getting created. Same issue

**Comment by PrabalS12** [comment]
has anyone of you found the solution to the same?

**Comment by saiyi123** [comment]
输入的视频跟音频文件名字有空格吗？

**Comment by Riyan-Abraham** [comment]
same issue here as well.

**Comment by r-ichar-d** [comment]
I have the same problem. 

_Firstly, if I'm seeking help and information in the wrong place I apologise, but I'm a complete newbie and would be grateful for any assistance._

The first time I test-used wav2lip, it worked very well, although the image quality was not so good (480p) - Kudos to Rudrhaba and team. Unfortunately it stopped working after a couple of days, so I then used the justinjohn modded version [justinjohn-03] available at [https://github.com/justinjohn0306] - which you need to use in a Google Colab - this worked very well with improved video quality (720p) and permits 1 minute file uploads. 

However, the justinjohn mod has also not worked properly (for me) for the last two days. Now, when using files can still be uploaded successfully, using either of the two available methods: 

- Method 1. YouTube video and GDrive audio links; or, 
- Method 2. from your own computer. 

Unfortunately both methods are now returning errors and the process cannot proceed further:

- Method 1. returns a FileNotFoundError*; and, 
- Method 2. returns a NameError* 

*see attached images for error messages).

If anyone has any information concerning fixes for these problems, please help! 

![wav2lip Upload method 1](https://github.com/Rudrabha/Wav2Lip/assets/143396413/ceb1e477-8c06-4d86-8cbd-75721a051a5a)
![wav2lip Upload method 2](https://github.com/Rudrabha/Wav2Lip/assets/143396413/386b227f-9808-41ea-a328-d8d5fd1ad3b1)

**Comment by justinjohn0306** [comment]
> <img alt="Screenshot 2023-07-11 at 10 15 35 PM" width="1309" src="https://user-images.githubusercontent.com/8232719/252707471-4b2db346-2c76-4cf4-91e4-fe0a08d481fb.png"> It worked the first time. Then same issue occuring over and over again. Tried to look for it but cant find it.

this issue has been fixed, try again :)

**Comment by r-ichar-d** [comment]
Thanks for the help. Will try again and let you know. Thanks again.

**Comment by Sn4kez** [comment]
Hi, I still get the error: 
![grafik](https://github.com/Rudrabha/Wav2Lip/assets/33695461/b19a1272-2ee6-45bb-8cbe-5cb74b295536)
